---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: example
spec:
  compositionSelector:
    matchLabels:
      app.tanzu.vmware.com/workload-type: web
  serviceAccountName: some-sa
  source:
    git:
      url: https://github.com/carto-labs/hello-world
      ref:
        branch: main
  build:
    env:
      - name: CGO_ENABLED
        value: "0"