---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: example
  labels:
    hello: goodbye
spec:
  compositionSelector:
    matchLabels:
      app.tanzu.vmware.com/workload-type: web
      app.tanzu.vmware.com/starting-point: image
  source:
    image: docker.io/crccheck/hello-world:latest
